org: ccalderon9411
app: reto-stofttek-nestjs
service: reto-stofttek-nestjs

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  deploymentBucket:
    name: reto-stofttek-nestjs

functions:
  getPersonas:
    handler: dist/lambda.handler 
    events:
      - http:
          path: personas
          method: get
          cors: true

  getPersonaById:
    handler: dist/lambda.handler 
    events:
      - http:
          path: personas/{id}
          method: get
          cors: true
          
  createPersona:
    handler: dist/lambda.handler 
    events:
      - http:
          path: personas
          method: post
          cors: true

  getStarWarsPeople:
    handler: dist/lambda.handler 
    events:
      - http:
          path: starwars-people
          method: get
          cors: true

  getStarWarsPerson:
    handler: dist/lambda.handler 
    events:
      - http:
          path: starwars-person/{id}
          method: get
          cors: true


plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies
