export const mockResponse = {
  nombre: 'Luke Skywalker',
  anio_nacimiento: '19BBY',
  color_ojos: 'blue',
  genero: 'male',
  color_cabello: 'blond',
  estatura: '172',
  peso: '77',
  color_piel: 'fair',
  planeta_origen: 'https://swapi.py4e.com/api/planets/1/',
  peliculas: [
    'https://swapi.py4e.com/api/films/1/',
    'https://swapi.py4e.com/api/films/2/',
    'https://swapi.py4e.com/api/films/3/',
    'https://swapi.py4e.com/api/films/6/',
    'https://swapi.py4e.com/api/films/7/',
  ],
  especies: ['https://swapi.py4e.com/api/species/1/'],
  naves_estelares: [
    'https://swapi.py4e.com/api/starships/12/',
    'https://swapi.py4e.com/api/starships/22/',
  ],
  vehiculos: ['https://swapi.py4e.com/api/vehicles/14/', 'https://swapi.py4e.com/api/vehicles/30/'],
  url: 'https://swapi.py4e.com/api/people/1/',
  fecha_creacion: '2014-12-09T13:50:51.644000Z',
  fecha_modificacion: '2014-12-20T21:17:56.891000Z',
};
